### ISSUE TITLE
Feature Request: Mocha Integration

### ISSUE THREAD

**Issue by chriscantu** [stuplum/astrolabe#7]
Hello, I would very much like to use astrolabe with mochajs.  I have tried to get it to run with grunt-mocha-protractor with no success.  When I run my tests, I get 'this' is undefined in the Astrolabe pages I created.  

`TypeError: Cannot call method 'findElement' of undefined`

Any suggestions?

Many thanks in advance

Chris

**Comment by chriscantu** [comment]
For anyone who is interested, I was able to get a VERY basic working example of Protractor, Astrolabe, Mocha and ChaiJS working.  I leveraged the grunt-mocha-protractor grunt task.  

The code can be found at:
https://github.com/chriscantu/protractor-astrolabe-mocha-example

**Comment by Droogans** [comment]
@chriscantu `grunt-mocha-protractor` is no longer required: see [an example of getting mocha to work with astrolabe](https://github.com/Droogans/ProtractorPageObjects/blob/master/test/protractor.conf.js#L14) here.

A test implementing mocha with astrolabe [can be found here](https://github.com/Droogans/ProtractorPageObjects/blob/master/test/stories/frontPage.js).

@stuplum You can close this issue now.

**Comment by chriscantu** [comment]
@Droogans The guy who showed you can use straight protractor must be a total loser! ;)

**Comment by Droogans** [comment]
Who, this guy?

![Ewwww.....](https://0.gravatar.com/avatar/d1e8290142049c30317c1711755fe333?d=https%3A%2F%2Fidenticons.github.com%2Fcc18611fd8c1391d28197e313425a37b.png&r=x&s=440)

From what I can gather, they _do_ look like a total loser. Good observation.
