### ISSUE TITLE
Less verbose api

### ISSUE THREAD

**Issue by dylang** [stuplum/astrolabe#9]
My team is thinking about writing something similar, but with a less verbose api. I was wondering what people think of an api like this:

```
// ./page-objects/sign-in.js
var al = require('astrolabe');

module.exports = {
    userName: al.model('username'), 
    password: al.model('password'),
    signIn: al.css('.sign-in'), 
    navigation: require('./tabs-not-signed-in); // another page-objects 
};
```

**Comment by chriscantu** [comment]
FYI: I created a pull-request to clean up the API a little bit.  

https://github.com/stuplum/astrolabe/pull/10

**Comment by chriscantu** [comment]
@dylang FYI: The first iteration of the api changes got merged.

**Comment by stuplum** [comment]
Closing as api changes have been merged.
